packages:
  - web-app

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - esbuild
  - puppeteer
  - puppeteer-core
  - sharp
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - prisma

publicHoistPattern:
  - "import-in-the-middle"
  - "require-in-the-middle"
