packages:
  - web-app

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - "@sentry/cli"
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - prisma

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
