packages:
  - web-app

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - "@vercel/speed-insights"
  - prisma
  - "puppeteer-core"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
