packages:
  - name: masumi-sync
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: main
        binary: false
        main: "main"
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment:
          ADMIN_KEY: ${ADMIN_KEY}
          SOKOSUMI_API_URL: ${SOKOSUMI_API_URL}
        annotations: {}
        limits: {}
        triggers:
          - name: masumi-sync
            sourceType: scheduler
            sourceDetails:
              # every minute
              cron: "* * * * *"
              withBody:
                name: "masumi-sync"
