region: fra
services:
  environment_slug: node-js
  envs:
    - name: RESEND_API_KEY
      value: ${RESEND_API_KEY}
    - name: BETTER_AUTH_SECRET
      value: ${BETTER_AUTH_SECRET}
    - name: BETTER_AUTH_URL
      value: ${BETTER_AUTH_URL}
    - name: NOREPLY_EMAIL
      value: ${NOREPLY_EMAIL}
  github:
    branch: main
    repo: masumi-network/sokosumi
  name: sokosumi-web-app
  source_dir: web-app
