publicHoistPattern:
  - "*eslint*"
  - "*prettier*"

ignoredBuiltDependencies:
  - "@prisma/engines"
  - "@swc/core"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/client"
