ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/client'
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
