region: fra
services:
  environment_slug: node-js
  envs:
    - name: RESEND_API_KEY
      value: ${RESEND_API_KEY}
    - name: RESEND_FROM_EMAIL
      value: ${RESEND_FROM_EMAIL}
    - name: BETTER_AUTH_SECRET
      value: ${BETTER_AUTH_SECRET}
    - name: BETTER_AUTH_URL
      value: ${BETTER_AUTH_URL}
    - name: GOOGLE_CLIENT_ID
      value: ${GOOGLE_CLIENT_ID}
    - name: GOOGLE_CLIENT_SECRET
      value: ${GOOGLE_CLIENT_SECRET}
    - name: MICROSOFT_CLIENT_ID
      value: ${MICROSOFT_CLIENT_ID}
    - name: MICROSOFT_CLIENT_SECRET
      value: ${MICROSOFT_CLIENT_SECRET}
    - name: LINKEDIN_CLIENT_ID
      value: ${LINKEDIN_CLIENT_ID}
    - name: LINKEDIN_CLIENT_SECRET
      value: ${LINKEDIN_CLIENT_SECRET}
    - name: APPLE_CLIENT_ID
      value: ${APPLE_CLIENT_ID}
    - name: APPLE_CLIENT_SECRET
      value: ${APPLE_CLIENT_SECRET}
    - name: REGISTRY_API_KEY
      value: ${REGISTRY_API_KEY}
    - name: ADMIN_API_KEY
      value: ${ADMIN_API_KEY}
    - name: NEXT_PUBLIC_NETWORK
      value: ${NEXT_PUBLIC_NETWORK}
    - name: PAYMENT_API_KEY
      value: ${PAYMENT_API_KEY}
    - name: PAYMENT_API_URL
      value: ${PAYMENT_API_URL}
    - name: SOKOSUMI_API_URL
      value: ${SOKOSUMI_API_URL}
    - name: REGISTRY_API_URL
      value: ${REGISTRY_API_URL}
    - name: ADMIN_KEY
      value: ${ADMIN_KEY}
  github:
    branch: main
    repo: masumi-network/sokosumi
  name: sokosumi-web-app
  source_dir: web-app
