name: ${DIGITALOCEAN_APP_NAME}
region: fra
services:
- name: sokosumi-web-app
  source_dir: web-app
  environment_slug: node-js
  envs:
    - key: NODE_ENV
      value: ${NODE_ENV}
      type: GENERAL
    - key: RESEND_API_KEY
      value: ${RESEND_API_KEY}
      type: SECRET
    - key: RESEND_FROM_EMAIL
      value: ${RESEND_FROM_EMAIL}
      type: GENERAL
    - key: BETTER_AUTH_SECRET
      value: ${BETTER_AUTH_SECRET}
      type: SECRET
    - key: BETTER_AUTH_URL
      value: ${BETTER_AUTH_URL}
      type: GENERAL
    - key: GOOGLE_CLIENT_ID
      value: ${GOOGLE_CLIENT_ID}
      type: GENERAL
    - key: GOOGLE_CLIENT_SECRET
      value: ${GOOGLE_CLIENT_SECRET}
      type: SECRET
    - key: MICROSOFT_CLIENT_ID
      value: ${MICROSOFT_CLIENT_ID}
      type: GENERAL
    - key: MICROSOFT_CLIENT_SECRET
      value: ${MICROSOFT_CLIENT_SECRET}
      type: SECRET
    - key: LINKEDIN_CLIENT_ID
      value: ${LINKEDIN_CLIENT_ID}
      type: GENERAL
    - key: LINKEDIN_CLIENT_SECRET
      value: ${LINKEDIN_CLIENT_SECRET}
      type: SECRET
    - key: APPLE_CLIENT_ID
      value: ${APPLE_CLIENT_ID}
      type: GENERAL
    - key: APPLE_CLIENT_SECRET
      value: ${APPLE_CLIENT_SECRET}
      type: SECRET
    - key: REGISTRY_API_KEY
      value: ${REGISTRY_API_KEY}
      type: SECRET
    - key: ADMIN_API_KEY
      value: ${ADMIN_API_KEY}
      type: SECRET
    - key: NEXT_PUBLIC_NETWORK
      value: ${NEXT_PUBLIC_NETWORK}
      type: GENERAL
    - key: PAYMENT_API_KEY
      value: ${PAYMENT_API_KEY}
      type: SECRET
    - key: PAYMENT_API_URL
      value: ${PAYMENT_API_URL}
      type: GENERAL
    - key: SOKOSUMI_API_URL
      value: ${SOKOSUMI_API_URL}
      type: GENERAL
    - key: REGISTRY_API_URL
      value: ${REGISTRY_API_URL}
      type: GENERAL
    - key: ADMIN_KEY
      value: ${ADMIN_KEY}
      type: SECRET
    - key: STRIPE_PUBLISHABLE_KEY
      value: ${STRIPE_PUBLISHABLE_KEY}
      type: SECRET
    - key: STRIPE_SECRET_KEY
      value: ${STRIPE_SECRET_KEY}
      type: SECRET
    - key: STRIPE_WEBHOOK_SECRET
      value: ${STRIPE_WEBHOOK_SECRET}
      type: SECRET
    - key: STRIPE_PRICE_ID
      value: ${STRIPE_PRICE_ID}
      type: GENERAL
  github:
    branch: main
    repo: masumi-network/sokosumi