name: ${DIGITALOCEAN_APP_NAME}
region: fra
services:
  - name: sokosumi-web-app
    github:
      branch: main
      repo: masumi-network/sokosumi
    environment_slug: node-js
    envs:
      - key: ADMIN_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${ADMIN_KEY}
        type: secret
